DROP TABLE IF EXISTS public."Historys";
DROP TABLE IF EXISTS public."basketsProducts";
DROP TABLE IF EXISTS public."Baskets";
DROP TABLE IF EXISTS public."Products";
DROP TABLE IF EXISTS public."Users";
DROP TABLE IF EXISTS public."Categorys";

-------------- Table: public.category
CREATE TABLE IF NOT EXISTS public."Categorys"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text
);
COMMENT ON TABLE public."Categorys"
    IS 'Категории товаров';

insert into "Categorys" (title)
values
    ('Ракетки'),
    ('Мячи'),
    ('Кроссовки'),
    ('Кеды'),
    ('Куртки'),
    ('Костюмы'),
    ('Рюкзаки'),
    ('Сумки');

----------- Table: public.Products
CREATE TABLE IF NOT EXISTS public."Products"
(
    id integer NOT NULL primary key generated by default as identity,
    title text,
    brand text,
    price double precision,
    category_id integer,
    size double precision,
    characteristic text,
    color text,
    foreign key (category_id) references "Categorys" (id)
);
COMMENT ON TABLE public."Products"
    IS 'Прайс-лист товаров';

insert into "Products" (title,brand,price,category_id,size,characteristic,color)
values
    ('Ракетка теннисная','Wilson', 25000, 1, 65.0, '300.0 гр.','red'),
    ('Ракетка теннисная','Solinco', 14000, 1, 68.0,'310.0 гр.','yellow'),
    ('Ракетка теннисная','Yonex', 29000, 1, 70.0,'270.0 гр.','black'),
    ('Мяч футбольный','Jogel', 2500, 2, 65.0, '400.0 гр.','white'),
    ('Мяч футбольный','Addidas', 16000, 2, 68.5,'430.0 гр.','silver'),
    ('Мяч футбольный','Nike', 3499, 2, 70.0,'450.0 гр.','green'),
    ('Мяч волейбольный','Mikasa', 5000, 2, 5,'250.0 гр.','yellow-blue'),
    ('Мяч волейбольный','Gala', 3000, 2, 4,'300.0 гр.','white'),
    ('Мяч волейбольный','Torres', 4700, 2, 3,'250.0 гр.','green'),
    ('Кроссовки','Puma',8700, 3, 41,'550.0 гр.','purple'),
    ('Кроссовки','Fila',5700, 3, 45,'650.0 гр.','blue'),
    ('Кроссовки','Reebok',7700, 3, 43,'450.0 гр.','white'),
    ('Кроссовки','Puma',8700, 3, 36,'550.0 гр.','purple'),
    ('Кроссовки','Fila',5700, 3, 38,'650.0 гр.','blue'),
    ('Кроссовки','Reebok',7700, 3, 39,'450.0 гр.','white'),
    ('Кеды','Puma',5700, 4, 36,'250.0 гр.','white'),
    ('Кеды','Fila',2700, 4, 38,'350.0 гр.','white'),
    ('Кеды','Reebok',4700, 4, 39,'350.0 гр.','white'),
    ('Куртка','Adidas',10500, 5, 48,'0','orange'),
    ('Куртка','Puma',15000, 5, 48.5,'0','blue'),
    ('Куртка','Columbia',20700, 5, 50.0,'0.','blue'),
    ('Куртка','Columbia',10700, 5, 54,'0','green'),
    ('Куртка','Adidas',15700, 5, 54.5,'0','pink'),
    ('Куртка','Puma',20700, 5, 56,'0','blue'),
    ('Костюм лыжный','Columbia',15500, 6, 48,'0','orange'),
    ('Костюм лыжный','Colmar',10000, 6, 48.5,'0','blue'),
    ('Костюм лыжный','Phenix',35700, 6, 50.0,'0.','blue'),
    ('Костюм лыжный','Columbia',15700,6, 48,'0','green'),
    ('Костюм лыжный','Colmar',10700, 6, 50,'0','pink'),
    ('Костюм лыжный','Phenix',35700, 6, 54,'0','blue'),
    ('Рюкзак','Deuter', 12500, 7, 48,'20 л.','green'),
    ('Рюкзак','Nike',11000, 7, 48.5,'80 л.','black'),
    ('Рюкзак','Naturehike',13700, 7, 50.0,'40 л.','pink'),
    ('Сумка','Columbia',2700, 7, 54,'0','orange'),
    ('Сумка','Adidas',5700, 7, 54.5,'0','pink'),
    ('Сумка','Puma',1700, 7, 56,'0','blue');


------------ Table: public.Users
CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL primary key generated by default as identity,
    name text,
    surname text,
    login text,
    passwd text,
    date_registration text,
    city text,
    country text,
    telf text,
    email text,
    is_block integer,
    is_admin integer
);

COMMENT ON TABLE public."Users"
    IS 'Клиенты и админы';

insert into "Users" (name,surname,login,passwd,date_registration,city,country,telf,email,is_block, is_admin)
values
    ('Ирина','Первая', 'i1','111', '2022-10-12','Ульяновск','Россия','890614234566','i1@mail.ru',0,1),
    ('Нина','Вторая', 'n2','222', '2022-10-12','Ульяновск','Россия','890614234566','n2@mail.ru',0,1),
    ('Иван','Петров', 'iv','123', '2022-10-12','Ульяновск','Россия','890614234566','iv@mail.ru',0,0),
    ('Иван','Дуров', 'iv','1234', '2022-01-12','Ульяновск','Россия','890614234566','ivvv@mail.ru',0,0);

-------- Table: public.historyBuyers
CREATE TABLE IF NOT EXISTS public."Historys"
(
    id integer NOT NULL primary key generated by default as identity,
    date_registration text,
    count_product integer,
    name_product text,
    brand text,
    price double precision,
    total_amount double precision,
    user_id integer,
    foreign key (user_id) references "Users" (id)
);

COMMENT ON TABLE public."Historys"
IS 'Истории заказов';


-------------- Table: public.Baskets (сичтаем,что админы тоже могут покупать!)
CREATE TABLE IF NOT EXISTS public."Baskets"
(
    id integer PRIMARY KEY,
    user_id integer not null unique references "Users" (id),
    last_date date,
    is_paid integer
);

COMMENT ON TABLE public."Baskets"
    IS 'Корзины';

insert into "Baskets" (id,user_id, last_date,is_paid)
values
    (1,1,'2022-10-12', 0),
    (2,2,'2022-10-12', 0),
    (3,3,'2022-10-12', 0),
    (4,4,'2022-10-12', 0);


-------------- Table: public.basketsProducts
CREATE TABLE IF NOT EXISTS public."basketsProducts"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    basket_id integer,
    product_id integer,
    count_product integer,
    total_amount double precision,
    foreign key (basket_id) references "Baskets" (id),
    foreign key (product_id) references "Products" (id)
);
COMMENT ON TABLE public."basketsProducts"
    IS 'Корзины-товары';

insert into "basketsProducts" (id,basket_id,product_id,count_product,total_amount)
values
    (1, 1, 1,1,25000),
    (2, 1, 2,1,14000),
    (3, 2, 1,1,25000),
    (4, 3, 1,1,25000);



